### ISSUE TITLE
BIO390: Show current lecture (today's lecture) in upcoming lectures

### ISSUE THREAD

**Issue by david-noe** [compbiozurich/compbiozurich.github.io#9]
URL: https://compbiozurich.org/courses/UZH-BIO390/

Currently, todays lecture is considered to be a "previous lecture".
I think it would be handy if lectures with date >**=** today would be considered as upcoming lecture, so that it's easier to find materials for ongoing lectures.

**Comment by mbaudis** [comment]
@david-noe Thanks - good point! Though this only happened when the site had changes on that day (rebuilding only happens upon changes, so "Upcoming" may contain old pages if nobody works on the site).

Fixed in https://github.com/compbiozurich/compbiozurich.github.io/commit/15a4d2afce00996509d8313f5a2d42d498494c3d
